### ISSUE TITLE
[Question(s)] Count in first array of ClientListDb

### ISSUE THREAD

**Issue by ddavaham** [planetteamspeak/ts3phpframework#118]
For starters, great library. Thank you.

Question: Why is the count of the results returned from clientListDB? Furthermore, why is it injected into the first result of the response? Lastly, if it is a must that the count is returned, would it not be better to do the following:

```
[
    'count' => 55,
    'clients' => [
        [
            "cldbid" => 3
            "client_unique_identifier" => TeamSpeak3_Helper_String 
            "client_nickname" => TeamSpeak3_Helper_String
            "client_created" => 1506382761
            "client_lastconnected" => 1506382761
            "client_totalconnections" => 0
            "client_description" => null
            "client_lastip" => null
        ], 
        [...]
    ]
]
```

**Comment by ddavaham** [comment]
Okay, so follow up. I just realized that the clientListDB has the `-count` flag hard-coded into the call. Is it possible to remove this? Or make it optional?

**Comment by ddavaham** [comment]
Including the count is not the issue. It actually is not the fault of the library at all. The response from the command that the library uses provides a list of clients from the TS Database, however, instead of setting the count off to the side, the response includes it as part of the first item in the collection. See below,

For legibility, I ran this through my application, but nothing has been modified at this stage;
```
array:4 [▼
  2 => array:9 [▼
    "count" => 93
    "cldbid" => 2
    "client_created" => 1506382761
    "client_lastconnected" => 1547418318
    "client_totalconnections" => 770
  ]
  5 => array:8 [▼
    "cldbid" => 5
    "client_created" => 1506383900
    "client_lastconnected" => 1547406468
    "client_totalconnections" => 884
  ]
  7 => array:8 [▼
    "cldbid" => 7
    "client_created" => 1506387914
    "client_lastconnected" => 1547415305
    "client_totalconnections" => 587
  ]
  11 => array:8 [▼
    "cldbid" => 11
    "client_created" => 1506403376
    "client_lastconnected" => 1529842938
    "client_totalconnections" => 405
  ]
]
```
So I had to implement a fix to strip out the count to produce this:


```
array:4 [▼
  2 => array:8 [▼
    "cldbid" => 2
    "client_created" => 1506382761
    "client_lastconnected" => 1547418318
    "client_totalconnections" => 770
    "client_description" => "Dev Overlord, Breaker Of Things"
  ]
  5 => array:8 [▼
    "cldbid" => 5
    "client_created" => 1506383900
    "client_lastconnected" => 1547406468
    "client_totalconnections" => 884
    "client_description" => null
  ]
  7 => array:8 [▼
    "cldbid" => 7
    "client_created" => 1506387914
    "client_lastconnected" => 1547415305
    "client_totalconnections" => 587
    "client_description" => null
  ]
  11 => array:8 [▼
    "cldbid" => 11
    "client_created" => 1506403376
    "client_lastconnected" => 1529842938
    "client_totalconnections" => 405
    "client_description" => null
  ]
]
```
For obvious security reasons, I removed the name, uid, description, and ip address to display it here.

**Comment by ronindesign** [comment]
Thanks for the quick response. I'm trying to have you clarify, specifically, what you prefer and want changed, and _why_.

Guessing / assuming from your implementation, you're trying to iterate over each client and maybe display / dump client properties.
Is the one-off count property on the first client messing up that iterative logic?
I understand the nature of the issue, but I'm trying to understand why it's a problem in your specific situation so any fix would address the correct problem.

On a side note: the response parsing is intentionally very straight forward / direct from what the server returns.
This is intentional as we don't want to be munging / magically parsing response data.
Otherwise, the next person down the line might be confused why there's no `count` returned, or worse, it's not returned in the expected location.
There are many weird, quarky things the server does that we refuse to "accommodate" for since any action on our part adds in our own "bias" and we want to keep the framework as agnostic and data as true to the source as possible.
This way developers who understand how the TS3 Query system works, get intuitive results that match the TS3 Query Manual.

**Comment by ddavaham** [comment]
Remove the count property from the first array. This allows developers to dump the data directly into a database instead of having to loop through the data to make sure that there are no other keys that are not supposed to be there.

Having a standardized structure for each item of the array allows for this. However, I understand where you are coming from, and agree with you. This is not big deal, I have my own fix in place, I am just curious as to why Teamspeak does it this way.

**Comment by ronindesign** [comment]
Thanks for clarifying. Yeah they do some strange / inconsistent stuff, we rarely get an explanation.
However, as we're not core TS3 devs, our hands are tied.
As an interface, we just try to make the framework integrate as intuitively and easily as possible, essentially just providing access via PHP to the same functionality that the query system provides, along with some helpers so people aren't having to rewrite the same sets of code logic.

We appreciate your understanding regarding this, we'd also like to know why on this and a great many other design choice mysteries we've encountered along the way...
I'll leave this open for now until we get a chance to review the return output a little closer.
Maybe adding an opt-in flag for "-count" would make sense if we can implement it in a non-disruptive way.
