### ISSUE TITLE
[Question] PSR-Standard

### ISSUE THREAD

**Issue by fkubis** [planetteamspeak/ts3phpframework#20]
Last year I did "fork" the framework and translated it to PSR-4 standard. Which was ok for this time, couse the project was not at github and there was no way to contribute.

Now you are at github 👍, my question is: will you use any PSR standard? I would create a fork and do the changes I did before.

Dont want to do this, until you said yes. Its a lot of work.

**Comment by ronindesign** [comment]
I know there is a version 2.0 of the framework that is in the works. If I remember correctly, @svenpaulsen stated that it will be PSR compliant, along with some other updates to bring the framework to a more current state.

One option instead of redoing all the work, might be to fork the project and then simply create a sub-directory such as `psr4_version` or something similar so that there is no merge conflicts and so the source is self-contained allowing for users to opt-in if they want to use the psr4 version.

However, I'm not sure how much code has been added to the current framework since last year, so you may have to integrate any additional changes. This would still seem to be less work than redoing all of your changes.

**Comment by svenpaulsen** [comment]
Version 2.0 will use namespaces. However I didn't intend to make these changes in the 1.x series as, like you said, it's a lot of work.
