### ISSUE TITLE
PHP7 fails recognizing the file path for viewer

### ISSUE THREAD

**Issue by uncovery** [planetteamspeak/ts3phpframework#42]
I am getting an "invalid file path" on my TeamSpeak3_Viewer_Html(...) request at TeamSpeak3/Node/Server.php:1681
It seems that the icon path is wrong, but I cannot tell how. I used the identical setup on PHP5 and it worked fine, with PHP7 it breaks.

**Comment by ronindesign** [comment]
Thanks for reporting this!

Could you provide a little more detail:
- The full error (so we can see specific output)
- If not indicated in the error, any relevant paths, e.g. the referenced icon(s)
- Some general info about your environment, such as operating system

Have you checked for valid path, access / permissions, etc? Is the framework just coming up with the wrong path, or is the file inaccessible from the framework?

**Comment by uncovery** [comment]
The full error is as follows:

`PHP Fatal error:  Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: invalid file path in /home/includes/ts3phpframework/libraries/TeamSpeak3/Node/S
erver.php:1681\nStack trace:
#0 /home/includes/ts3phpframework/libraries/TeamSpeak3/Viewer/Html.php(417): TeamSpeak3_Node_Server->transferInitDownload(36816, 0, Object(TeamSpeak3_Helper_String))
#1 /home/includes/ts3phpframework/librar
ies/TeamSpeak3/Viewer/Html.php(389): TeamSpeak3_Viewer_Html->getSuffixIconServer()
#2 /home/includes/ts3phpframework/libraries/TeamSpeak3/Viewer/Html.php(143): TeamSpeak3_Viewer_Html->getSuffixIcon()
#3 /home/includes/ts3phpframework/l
ibraries/TeamSpeak3/Node/Abstract.php(194): TeamSpeak3_Viewer_Html->fetchObject(Object(TeamSpeak3_Node_Server))
#4 /home/spiesshofer/public_html/test/index.php(41): TeamSpeak3_Node_Abstract->getViewer(Object(TeamSpeak3_Viewer_Html))
#5
 /home/spiesshofer/public_html/test/index.php(24): umc_ts_viewer()
#6 {main}\n  thrown in /home/includes/ts3phpframework/libraries/TeamSpeak3/Node/Server.php on line 1681`

The environment is: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.1.9 

The code I am using is this here: http://pastebin.centos.org/204161/
In that code, if I comment out lines 23,24,25 it works fine (just w/o icons).

**Comment by ronindesign** [comment]
Great, thank you for providing this extra information, I appreciate it.

I'll look into this and see what could be causing the issue.

**Comment by ronindesign** [comment]
I'm still looking into this, but quick update so far:
- I haven't been able to reproduce your error for any version of PHP for my test ts3server.
- The error line listed in stack trace involves getting the icon id for `virtualserver_icon_id`
- The error message is coming from the ts3server server query's response after executing the `ftinitdownload` command, with the response being that the path is invalid.

So, this would mean that either:
- Path is being compiled incorrectly by framework (this is possible, since PHP5 works for you)
- There is an issue with the icon file / path (unlikely, since PHP5 works)

I'm having trouble testing this as I can't reproduce a failed scenario to work from...
If possible, you could try some troubleshooting by comparing what the framework gives you for `TeamSpeak3_Node_Server::iconGetName("virtualserver_icon_id")` and what files you have in your teamspeak's `files/` directory to see if that icon file exists.

For example:
```php
require_once("ts3phpframework/libraries/TeamSpeak3/TeamSpeak3.php");
// connect to local server, authenticate and spawn an object for the virtual server on port 9987
$ts3_VirtualServer = TeamSpeak3::factory("serverquery://username:password@X.X.X.X:10011/?server_port=9987");
echo 'Icon path: ' . $ts3_VirtualServer->iconGetName('virtualserver_icon_id');
```

In my case, even when the above returns value of `(int) 0` the path comes out to `/icon_0`, but the framework handles this and I receive no error.
I'm using master version of framework, v1.1.25 from:
https://github.com/planetteamspeak/ts3phpframework/archive/master.zip

I'm still looking into this, but any further troubleshooting results or information would be helpful, as I still can't get a failure under PHP7...

**Comment by uncovery** [comment]
your iconGetName returns Icon path: /icon_3798831355

**Comment by ronindesign** [comment]
So that is probably why you are getting an error, as the icon does not exist.
You could try changing the teamspeak's Virtual Server Icon (right click top server line in TeamSpeak3 Client -> Edit Virtual Server, then in pop-up set the icon, its on the right, about 4 rows down).
After setting the icon, see if you still get the same error.

To answer your questions and provide more detail into the framework logic:

In your few lines:
```php
 $ts_viewer = new TeamSpeak3_Viewer_Html(
        "admin/img/teamspeak/viewer/",
        "admin/img/teamspeak/flags/",
        "data:image",
        $pattern
    );
```
The first two paths don't seem to have anything to do with the error you're getting.
The error comes as a result of instantiating a new `TeamSpeak3_Viewer_Html` object, which in turn runs the `virtualserver_icon_id` lookup logic.
Maybe the teamspeak database has an icon ID configured, but that file doesn't actually exist (as you mentioned there are no icons in `/teamspeak/files/virtualserver_1/internal/icons`) and so the ts3server query command `ftinitdownload` returns the invalid path error.

The logic surround the error is as follows:

- Error message comes from thrown exception:
```php
if(array_key_exists("status", $download) && $download["status"] != 0x00)
{
  throw new TeamSpeak3_Adapter_ServerQuery_Exception($download["msg"], $download["status"]);
}
```
So we know the `$download["status"]` was non-success (e.g. not `0x00`) and the message received is set a text for exception, that is `invalid file path` given from `$download['msg']`.

We see `$download['msg']` is the response from Server Query command:
```php
$download = $this->execute("ftinitdownload", array("clientftfid" => $clientftfid, "cid" => $cid, "name" =     > $name, "cpw" => $cpw, "seekpos" => $seekpos))->toList();
```
This is executed directly on the ts3server and it has it's own relative paths.
Meaning, when we pass in `$name = '/icon_3798831355'`, ts3server tries to find this file (icon) in it's file directories.

In testing, when I set an icon I got a path `/icon_3988646452`.
When I look in my files for this icon, I find it at:
`files/virtualserver_1/internal/icons/icon_3988646452`
So if you don't have icons or files there, then there is a problem.

Maybe these icon files got deleted or moved? But the ts3server still thinks there in those directories, and when they're not, there is an error.
If you remove the icon from your ts3server for example, it will remove that icon_id from the ts3server's database, and then from the file system itself so there is no mismatch.

**Comment by uncovery** [comment]
ahhhh. Yes, I found the files on my old server and moved them over, now it works fine. I was not aware that the files directory contained files that break the viewer if missing.

So I guess we can close this one. As a request I would think it would be great if there would be a better error message than a "file not found" for a command that has a path in it when the file not found has nothing to do with the path you entered.. it's a bit confusing.

Anyhow, thanks a lot for the help!

**Comment by ronindesign** [comment]
Great, I'm glad we got it figured out.

Regarding your thoughts, I had the same idea, I think maybe there should be a clearer indication when an error message is returned directly from the ts3server's query interface, so that developers don't think it's the framework having an issue.
On the other hand, the exception type is specified as `TeamSpeak3_Adapter_ServerQuery_Exception` which, to me, indicates an error from the adapter.

Honestly, I think this was a bit of a red herring... the command being called just happened to take paths, and unfortunately the error message also happens to mentions an "invalid file path" so it's a very obvious first thought that the paths you're using are wrong for some reason, when in fact, the error is actually unrelated.

Lastly, I just want to point out that the framework actually doesn't have any problem with the icon files being missing, nor does the ts3server really care initially (this is why the ts3server can startup without exception). However, the crisis for both occurs when there is a mismatch between  the ts3server's db and the filesystem, hence one things there /should/ be a file, and the other that file doesn't exist.

**Comment by uncovery** [comment]
You are absolutely right. I was wondering since there is the line `throw new TeamSpeak3_Adapter_ServerQuery_Exception($download["msg"], $download["status"]);` but there is no download failed message or anything that would tell the users that downloading an icon that the server knows is in its db missing at path X.

Clearly the whole thing is obscure since I made a mistake when upgrading by not including the file folder.

**Comment by ronindesign** [comment]
I definitely agree it's obscure. There have been many times working with the framework, ts3server, and frequently with the server query interface that things are overly simplified, too generic or ambiguous, leading to confusion about multiple meanings or contexts for something.

It's pretty frustrating in general and I whole heartily empathize with you on this. From the framework's side of things, maybe there is something we can do do improve the error, type of error, or format for which these "query error" exceptions happen, so that developers understand it's the server query faulting out.

I'll mark this issue as support, enhancement and see if I can find a clearer, more full way tof representing these errors.

Thanks again for the feedback on this, really appreciate your comments and time in this!

**Comment by uncovery** [comment]
Thinking about it, maybe a debug mode would be a good thing?

**Comment by ronindesign** [comment]
Good thought, would this work something like a "verbose" mode, enabled via global flag?

Additional debug code would then need to be introduced that:
- Checks if flag is enabled
- Adds additional output, logging, and other relevant details, especially when there is fault

**Comment by uncovery** [comment]
I usually add code in the shape of `if ($debug) {$debug[] = $time . " Starting process X with variables Z = $z and Y =$y);`  and dump that to a logfile or echo.
Or, which is a bit more intensive, you do all pre-checks for anything that could fail. Since you working with an external server that might just drop the ball on you, maybe you need a mox of both

**Comment by ronindesign** [comment]
And what level of scope would this be introduced?

Obvious places might be common methods (like the core `execute()`query command), but introducing this logic in every method might be overkill?

It seems to me a balance of both would be needed, but from a developer's perspective, where would you find it most useful personally?

Some is probably better than none, even if that means lack of consistency, but would adding the debug logic to /just/ a few of the core methods be useful enough? Or should more methods / areas of concern also contain the debug logic because lack of consistency might be more confusing...

**Comment by uncovery** [comment]
I don't think you need it everywhere. Anyhow you have to start somewhere. So first introduce the general logic, and then roll it out first to where it matters most.

**Comment by ronindesign** [comment]
Sounds good, thanks again for the feedback.
