### ISSUE TITLE
channel sorting

### ISSUE THREAD

**Issue by burakataoglu** [planetteamspeak/ts3phpframework#59]
Can I sort channels by names?

http://prntscr.com/i0fpce

I want that like
...:10050
...:10097
...

**Comment by ronindesign** [comment]
@burakataoglu I'm assuming you're using the TSViewer.
Sorting by channel names is not possible.
The TSViewer simply follows the same sorting used by the TeamSpeak3 Client, matching the existing channel order set on the server.

I suppose you could pre-sort the channels on the TeamSpeak server, so then the TSViewer would show them in the order you desire.
You could do this manually via TeamSpeak3 Client when connected to the server, or programmatically using the framework via Server Query. I.e., when a new channel is to be added, then add it in the correct order.

Another option is to extend the default TSViewer or create a new viewer with desired layout.
This way, you could modify the channel list output behavior so that all child channels are sorted alphanumerically.
