### ISSUE TITLE
invalid parameter exception when trying to access subChannelGetById with high channel ids

### ISSUE THREAD

**Issue by Bloodsoul** [planetteamspeak/ts3phpframework#60]
I am referencing to this method: https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___channel.html#a7b5b5a32d8660534e61cdc3593f0052e

Everytime I try to access subChannelGetById from a channel object, I get the following exception. Even if the given cid is a valid id of a subchannel.

Exception: 
> Fatal error: Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: invalid parameter in planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Abstract.php:582

Example code:
```php
$ts = TeamSpeak3::factory($server);
$channel = $ts->channelGetById(32);
$channel->subChannelGetById(703);  // fails with above exception
```

The following snippet actually works:
```php
array_key_exists(703, $channel->subChannelList())
```

**Comment by Bloodsoul** [comment]
It seems to have something to do with the higher channel id. If I remember correctly, it has also thrown this exception, when I tried to access channelGetById with the same id.

**Comment by ronindesign** [comment]
Thanks for opening and detailing this issue @Bloodsoul, we appreciate it!

Would you mind providing your PHP version as well?

I'll try and reproduce this from my end as well, and dig into what might be causing this.

**Comment by Bloodsoul** [comment]
I'm currently using PHP 7.1.13

**Comment by ronindesign** [comment]
I had a chance to test this yet, but there might be some trouble with `$this->channelList` not being updated correctly, it could very well be a logic bug.

Looks like `subChannelGetById($cid)` is checking via `$this->getParent()->channelList()`, but then returning `$this->channelList[(string) $cid];`, which should be set correctly after the `channelList()` call.

However, in the meantime I would suggest a few work arounds since, as you pointed out, the sub-channel ID key exists:
- Use array returned directly from `subChannelList()`:
```php
$subchannel = $channel->subChannelList()['703']; // Make sure to use string index.
```
- You could try to get subchannel directly from `TeamSpeak3\Node\Server::channelList()`:
```php
$subchannel = $ts->channelList()['703']; // Make sure to use string index.
```
- Also forcing reset of channel list (although your code example shows you check list immediately after connecting, so channelList should be fresh):
```php
$ts->channelListReset();
$channel->subChannelGetById(703);  // fails with above exception
// Or
$ts->channelListReset();
$subchannel = $ts->channelList()['703']; // Make sure to use string index.
```

I'll try and reproduce this, sorry for the delay as I've not had much time recently.

**Comment by svenpaulsen** [comment]
Please re-test with the latest master. You should get a more meaningful error message now.
