### ISSUE TITLE
Getting a list of Teamspeak3 Servers.

### ISSUE THREAD

**Issue by MegaITA** [planetteamspeak/ts3phpframework#70]
Is there any function to get all the teamspeak3 servers controlled by the server query? I've got only a query for a  node and i want to get all the servers into the node and control them.

**Comment by Sebi94nbg** [comment]
So you want to get all _virtual_ TeamSpeak 3 servers of a single TeamSpeak 3 server instance, right?

```
// load framework files
require_once("libraries/TeamSpeak3/TeamSpeak3.php");

// connect to local server, authenticate and spawn an object for the instance
$ts3_instance = TeamSpeak3::factory("serverquery://username:password@127.0.0.1:10011/?tls=1");

$ts3_virtualservers = $ts3_instance->serverList();

foreach($ts3_virtualservers as $server) {
        echo $server->virtualserver_name . " (Virtual Server ID: " . $server->virtualserver_id . ")<br>";
}
```
This should return a list with all virtual TeamSpeak 3 servers (name + id). I haven't tested it, so there might be a syntax issue.

**Comment by ronindesign** [comment]
@Sebi94nbg's code should work to get list of servers for that host.

Note: I'm not sure what kind of _control_ you're doing, but async is not built into the framework so you probably will have a hard time controlling "all of them, at the same time".

Otherwise, you should be able to connect and issue commands to each virtual server in the list `$ts3_virtualservers`, again just be mindful not to block yourself when trying to make multiple calls.

**Comment by MegaITA** [comment]
Thank you! I'm working on a teamspeak 3 panel for my hosting!
