### ISSUE TITLE
Searchable version of the documentation

### ISSUE THREAD

**Issue by Daniel90w** [planetteamspeak/ts3phpframework#99]
As "Strg + f" doesn't work there i have no idea on how to find something in there. I mean it technically works if you already know where to find it, but that's at least partially still the same problem.

Is there a fully searchable document?

Or how else can i find out how things are named in the framework except for going through the whole code?

For example:
How would i find Serverlisting?

**Comment by ronindesign** [comment]
I agree, the current format for documentation is not entirely accessible.

Any suggestions for an alternative format?

Here are some methods for searching documentation, some of which I use frequently:

**Search using google**
If you google `serverlisting site:https://docs.planetteamspeak.com/ts3/php/framework/`, it will search documentation fairly well, but still you need to know correct search term, this is a bit like searching code base, but at least shows model relationships better...

**Search GitHub code repository**
You've already mentioned this one, but still including for completeness.
https://github.com/planetteamspeak/ts3phpframework/search?q=serverlist&unscoped_q=serverlist
(Again, this requires knowing correct search term...)

**Search TeamSpeak3 Server Query Manual**
When trying to find correct term for searching in above methods, you could look for an equivalent command in the server query manual (which you can CTRL+F through since it's a PDF).

**Download and search documentation site (HTML)**
Manually download site from one of:
- https://docs.planetteamspeak.com/ts3/php/framework
- https://github.com/ronindesign/ts3phpframework/tree/tmp/public/doc/html

Other than this, I don't have more to offer you in terms of a solution, but I hope it helps.

**Comment by Daniel90w** [comment]
No, sorry, i have no idea. But your workarounds definitely help. Thanks!

**Comment by ronindesign** [comment]
Great, glad it's helpful. Closing this for now, please let us know if we can be of further assistance!

Thanks for the tip @dampfklon, we'll see if @svenpaulsen can enable that on the document site.
